@ECHO OFF
cd sta03708
"C:\Renesas\e2_studio\GNUSHv12.01-ELF\sh-elf\bin/sh-elf-gcc"  -c -fno-builtin  -DINTERNAL_NEWLIB -DDEFINE_MALLOC -DDEFINE_FREE    -DDEFINE_REALLOC -DDEFINE_CALLOC  -mb -m2 -Os -ffunction-sections -fdata-sections -fno-function-cse -funit-at-a-time -falign-jumps   -IC:/Renesas/e2_studio/GNUSHv12.01-ELF/sh-elf/bin/newlib/include -IC:/Renesas/e2_studio/GNUSHv12.01-ELF/sh-elf/bin/newlib/libm/common   C:/Renesas/e2_studio/GNUSHv12.01-ELF/sh-elf/bin/newlib/libc/common/*.c C:/Renesas/e2_studio/GNUSHv12.01-ELF/sh-elf/bin/newlib/libc/syscalls/*.c  C:/Renesas/e2_studio/GNUSHv12.01-ELF/sh-elf/bin/newlib/libc/ctype/*.c  C:/Renesas/e2_studio/GNUSHv12.01-ELF/sh-elf/bin/newlib/libc/stdio/*.c  C:/Renesas/e2_studio/GNUSHv12.01-ELF/sh-elf/bin/newlib/libc/stdlib/*.c  C:/Renesas/e2_studio/GNUSHv12.01-ELF/sh-elf/bin/newlib/libc/string/*.c  C:/Renesas/e2_studio/GNUSHv12.01-ELF/sh-elf/bin/newlib/libc/sys/sh/*.c C:/Renesas/e2_studio/GNUSHv12.01-ELF/sh-elf/bin/newlib/libc/sys/sh/*.S -IC:/Renesas/e2_studio/GNUSHv12.01-ELF/sh-elf/bin/newlib/libc/sys/sh/sys >error_log 2>&1
"C:\Renesas\e2_studio\GNUSHv12.01-ELF\sh-elf\bin/sh-elf-gcc"  -c -fno-builtin  -DINTERNAL_NEWLIB -DDEFINE_MALLOC -DDEFINE_FREE    -DDEFINE_REALLOC -DDEFINE_CALLOC  -DINTEGER_ONLY -o vfiprintf.o -mb -m2 -Os -ffunction-sections -fdata-sections -fno-function-cse -funit-at-a-time -falign-jumps    -IC:/Renesas/e2_studio/GNUSHv12.01-ELF/sh-elf/bin/newlib/include -IC:/Renesas/e2_studio/GNUSHv12.01-ELF/sh-elf/bin/newlib/libm/common   C:/Renesas/e2_studio/GNUSHv12.01-ELF/sh-elf/bin/newlib/libc/stdio/vfprintf.c  >error_log 2>&1
"C:\Renesas\e2_studio\GNUSHv12.01-ELF\sh-elf\bin/sh-elf-gcc"  -c -fno-builtin  -DINTERNAL_NEWLIB -DDEFINE_MALLOC -DDEFINE_FREE    -DDEFINE_REALLOC -DDEFINE_CALLOC  -DINTEGER_ONLY -o vfiscanf.o -mb -m2 -Os -ffunction-sections -fdata-sections -fno-function-cse -funit-at-a-time -falign-jumps    -IC:/Renesas/e2_studio/GNUSHv12.01-ELF/sh-elf/bin/newlib/include -IC:/Renesas/e2_studio/GNUSHv12.01-ELF/sh-elf/bin/newlib/libm/common   C:/Renesas/e2_studio/GNUSHv12.01-ELF/sh-elf/bin/newlib/libc/stdio/vfscanf.c  >error_log 2>&1
"C:\Renesas\e2_studio\GNUSHv12.01-ELF\sh-elf\bin/sh-elf-gcc"  -c -fno-builtin  -DINTERNAL_NEWLIB -DDEFINE_MALLOC -DDEFINE_FREE    -DDEFINE_REALLOC -DDEFINE_CALLOC  -DSTRING_ONLY  -o svfprintf.o -mb -m2 -Os -ffunction-sections -fdata-sections -fno-function-cse -funit-at-a-time -falign-jumps    -IC:/Renesas/e2_studio/GNUSHv12.01-ELF/sh-elf/bin/newlib/include -IC:/Renesas/e2_studio/GNUSHv12.01-ELF/sh-elf/bin/newlib/libm/common   C:/Renesas/e2_studio/GNUSHv12.01-ELF/sh-elf/bin/newlib/libc/stdio/vfprintf.c  >error_log 2>&1
"C:\Renesas\e2_studio\GNUSHv12.01-ELF\sh-elf\bin/sh-elf-gcc"  -c -fno-builtin  -DINTERNAL_NEWLIB -DDEFINE_MALLOC -DDEFINE_FREE    -DDEFINE_REALLOC -DDEFINE_CALLOC  -DSTRING_ONLY  -o svfscanf.o -mb -m2 -Os -ffunction-sections -fdata-sections -fno-function-cse -funit-at-a-time -falign-jumps    -IC:/Renesas/e2_studio/GNUSHv12.01-ELF/sh-elf/bin/newlib/include -IC:/Renesas/e2_studio/GNUSHv12.01-ELF/sh-elf/bin/newlib/libm/common   C:/Renesas/e2_studio/GNUSHv12.01-ELF/sh-elf/bin/newlib/libc/stdio/vfscanf.c  >error_log 2>&1
"C:\Renesas\e2_studio\GNUSHv12.01-ELF\sh-elf\bin/sh-elf-gcc"  -c -fno-builtin  -DINTERNAL_NEWLIB -DDEFINE_MALLOC -DDEFINE_FREE    -DDEFINE_REALLOC -DDEFINE_CALLOC  -DSTRING_ONLY  -DINTEGER_ONLY  -o svfiprintf.o -mb -m2 -Os -ffunction-sections -fdata-sections -fno-function-cse -funit-at-a-time -falign-jumps    -IC:/Renesas/e2_studio/GNUSHv12.01-ELF/sh-elf/bin/newlib/include -IC:/Renesas/e2_studio/GNUSHv12.01-ELF/sh-elf/bin/newlib/libm/common   C:/Renesas/e2_studio/GNUSHv12.01-ELF/sh-elf/bin/newlib/libc/stdio/vfprintf.c  >error_log 2>&1
"C:\Renesas\e2_studio\GNUSHv12.01-ELF\sh-elf\bin/sh-elf-gcc"  -c -fno-builtin  -DINTERNAL_NEWLIB -DDEFINE_MALLOC -DDEFINE_FREE    -DDEFINE_REALLOC -DDEFINE_CALLOC  -DSTRING_ONLY  -DINTEGER_ONLY  -o svfiscanf.o -mb -m2 -Os -ffunction-sections -fdata-sections -fno-function-cse -funit-at-a-time -falign-jumps    -IC:/Renesas/e2_studio/GNUSHv12.01-ELF/sh-elf/bin/newlib/include -IC:/Renesas/e2_studio/GNUSHv12.01-ELF/sh-elf/bin/newlib/libm/common   C:/Renesas/e2_studio/GNUSHv12.01-ELF/sh-elf/bin/newlib/libc/stdio/vfscanf.c  >error_log 2>&1
cd ..
@ECHO ON